### ISSUE TITLE
Feedback from the Chairs (01/2021)

### ISSUE THREAD

**Issue by boucadair** [boucadair/draft-btw-add-home-network#4]
To the authors –

Would it be reasonable to expand this to be more generally applicable to anyplace DHCP/RA was being used?  AKA Drop the HOME reference in the title and throughout the document? So this draft would be more simply:    “DHCP and Router Advertisement Options for Encrypted DNS Discovery”?

The material in the draft seems applicable across SMB and even enterprise networks as well as other situations.   Certainly, it may be useful add a couple of descriptive sections that mention these other use environments, but given that the ADD group has done extensive discussion around DHCP at the September Interim and on list, where there was no specific “in the home” restriction discussed, it would seem reasonable to fold these other environments into one document.

If there are issues that you feel are outstanding and need to be discussed, we can also add those to the topics for the Jan 27 Interim.    The Interim format will be focused on discussion and not much in the way of presentation mode, so pulling up issue topics would helpful to the agenda and this document.

**Comment by tojens-ietf** [comment]
I do think this would be a smooth evolution that would go over well with the WG. To be honest the draft has pretty much reached that place already. 

> The Interim format will be focused on discussion and not much in the way of presentation mode, so pulling up issue topics would helpful to the agenda and this document.

It would be worth bringing up the open question about including or not including DoH templates directly in options. If the WG will express an opinion on that, the case will be pretty strongly that this draft is ready for adoption (the number of feedback-driven revisions shows that it has been adopted informally already).

**Comment by boucadair** [comment]
Changes can be tracked as well at:

https://www.ietf.org/rfcdiff?difftype=--hwdiff&url1=draft-btw-add-home&url2=https://raw.githubusercontent.com/boucadair/draft-btw-add-home-network/master/draft-btw-add-home.txt
